apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ttl.sh/backend-mern-1:23h  # Replace with your image
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: MONGO_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-cm
              key: PORT

---
apiVersion: v1
kind: Service
metadata:
  name: backend  # This name is used in Ingress routing
  namespace: traefik
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  #type: ClusterIP #ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
  namespace: traefik
data:
  MONGO_URI: "mongodb://mongodb.traefik.svc.cluster.local:27017/mern-sts-todo"
  PORT: "5000"
